---

- name: Install Visual Studio Code (visual-studio-code-bin from AUR)
  shell: yay -S --noconfirm visual-studio-code-bin
  become: true
  become_user: builduser
  args:
    creates: /usr/bin/code
  when: not ansible_check_mode
